language: go
sudo: required

go:
  - 1.7

services:
  - redis-server

install:
  # pull go dependencies
  - make dependencies

script:
  # add blacklisted domains to redis
  - make populate_redis
  # run doic go-tests
  - make test --no-print-directory
  # test doic_cli
  - make test_cli

after_success:
  ### doic
  # statically compile doic
  - make stat
  # upload doic to binder
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/doic*` --form path=doic/ --form filename=doic-latest-linux-amd64 https://cryo.unixvoid.com/upload
  ### doic_cli
  # statically compile doic_cli
  - make clean stat_cli
  # upload doic_cli to binder
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/doic*` --form path=doic/ --form filename=doic_cli-latest-linux-amd64 https://cryo.unixvoid.com/upload
  ### upload doic to rkt
  - make clean build_travis_aci
  # grab pub/pri keys
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  # sign aci
  - cp deps/sign.sh . && chmod +x sign.sh
  - ./sign.sh $GPG_SEC
  # upload aci to binder
  - curl -i --form sec=$BINDER_SEC --form file=@doic-latest-linux-amd64.aci --form path=rkt/doic/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@doic-latest-linux-amd64.aci.asc --form path=rkt/doic/ https://cryo.unixvoid.com/upload
